### ISSUE TITLE
jPLY issue

### ISSUE THREAD

**Issue by kephale** [imagej/imagej-mesh-io#1]
https://forum.image.sc/t/imagej-mesh-io-0-1-2-jar-error/22878

**Comment by ctrueden** [comment]
I believe this happened because I uploaded `imagej-mesh-io` and `jply` to the Java-8 update site this morning—so that Fiji could export STL files without the SciView update site enabled—and a bug in the Updater caused the `jply` JAR to be removed as a dependency of `imagej-mesh-io`, because that dependency was previously obsolete, and only now being reintroduced.

I have hopefully addressed the issue by manually readding `jply` as a dependency of `imagej-mesh-io` in the `db.xml.gz`. Please try updating Fiji again and see if it wants to install `jply` now.

**Comment by ctrueden** [comment]
I filed imagej/imagej-updater#74 for the Updater bug.
